//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTeam1Hackathon_2019.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public long MarkId { get; set; }
        public Nullable<long> StudentId { get; set; }
        public Nullable<long> ModuletId { get; set; }
        public Nullable<long> CurrentCourseId { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Modules Modules { get; set; }
        public virtual Student Student { get; set; }
    }
}
